---
- hosts: all
  gather_facts: false
  become: yes
#  become_method: su
#  become_user: sysadmin
  tasks:
  - name: deploy sample file to remote machines
    copy:
      src: /home/sysadmin/admin6 
      dest: /home/sysadmin/admin6
