---
- hosts: all
  gather_facts: false
  become: yes
#  become_method: su
#  become_user: sysadmin
  tasks:
  - name: deploy sample file to refile:
    file:
      path: /home/sysadmin/admin6.conf
      state: touch
      owner: sysadmin
      group: sysadmin
      mode: '0644'
    
